# These are supported funding model platforms

github: cybersorcerer
ko_fi: cybersorcerer

# Other options (uncomment and configure if needed):
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# buy_me_a_coffee: # Replace with your Buy Me a Coffee username
# liberapay: # Replace with your Liberapay username
# custom: ["https://example.com"] # Replace with custom donation URL
