name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.9.9, v1.0.0, etc.

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build all platforms
        run: make build-all
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Create release packages
        run: make release
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Generate release notes
        id: release_notes
        run: |
          cat > release_notes.md << 'EOF'
          ## Kick Assembler Language Server ${{ steps.get_version.outputs.VERSION }}

          ### Installation

          **Unix/Linux/macOS:**
          ```bash
          curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh | bash
          ```

          **Windows (PowerShell):**
          ```powershell
          iwr -useb https://raw.githubusercontent.com/${{ github.repository }}/main/install.ps1 | iex
          ```

          **Manual Installation:**
          Download the appropriate archive for your platform below, extract it, and run the included install script.

          ### Supported Platforms

          - macOS (Intel): `kickass_ls-${{ steps.get_version.outputs.VERSION }}-darwin-amd64.tar.gz`
          - macOS (Apple Silicon): `kickass_ls-${{ steps.get_version.outputs.VERSION }}-darwin-arm64.tar.gz`
          - Linux (x86_64): `kickass_ls-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz`
          - Linux (ARM64): `kickass_ls-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.gz`
          - Windows (x86_64): `kickass_ls-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip`

          ### What's Included

          Each archive contains:
          - `kickass_ls` binary (or `kickass_ls.exe` on Windows)
          - Configuration files (`kickass.json`, `mnemonic.json`, `c64memory.json`)
          - Installation script for your platform

          ### Documentation

          For setup instructions and documentation, see the [README](https://github.com/${{ github.repository }}#readme).
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body_path: release_notes.md
          files: |
            dist/releases/*.tar.gz
            dist/releases/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload checksums
        uses: softprops/action-gh-release@v1
        with:
          files: dist/releases/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
